platform :ios, '14.0'
source "https://cdn.cocoapods.org/"

# Podfile này CHỈ ĐỂ THAM KHẢO - cho thấy source gốc của VBotPhoneSDK
# MAUI project dùng VBotPhoneSDK.xcframework trực tiếp (đã download qua binding project)
# Giống tài liệu: https://vbotdevteam.github.io/vbot-documentation/ios-sdk/cau-hinh-sdk.html

target 'VBotIosWrapper' do
  use_frameworks! :linkage => :static

  pod 'VBotPhoneSDKiOS-Public', :git => 'https://github.com/VBotDevTeam/VBotPhoneSDKiOS-Public.git', :tag => '1.1.9'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
    end
  end
end
